language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    before_install:
    - npm i -g npm@latest
    - sudo apt-get install -y librtlsdr-dev libflac-dev rpm
cache:
  directories:
  - node_modules
notifications:
  email: false
script:
- npm test
- npm run dist
deploy:
  provider: releases

  api_key:
    secure: NGLdKAoh9HM5dNMfQh29+rubpRTF3IkXXH0+iJl10gN+Ic1A6e70xHB8rJf8ViGVTPa2Ak7ydcFdau+KJP4gkW4ubjP89iBJX+zaouWnzLsLUp1kAG+UEpxFwmRLjGNIuwixLB7RbdDejsiH2dM3DhzIDRSzTl45ZQhZMoj5vTSUj6HwPEPjs2TQ2QfU6C0ZoINDD8MsNZXj3DZnY0mgulokg+saT1CX5wIwsoiqndFEgO0ZoJBXsx3O8Go3Eb5yvjZHIGo6uaFKY8R1ryUu28nIuP0hh9I695adX2I4lOVYz6mk4DpQ6SBt97z69gtoUriyD7fVMkKSmfxTcENvFCjcgFRYtgl8NbsvFG6Nj42tweGGK497a+CyM06uoAM+eQmcV/hdW1a8sewtxxlheSW7LXr1QejcK5PiHUuPQweNVx4VNnmpvopF+83QaRP9VEPIY5h7qGsUN9hc4GwabkYAcd5fHDtb6p40RGLTwv6FQU7cRoi2wTtSaV+GJqYW4Y8M9eyl8auxD/J85AuDBt9Sn+LwoR5sQqwxlOBNU8p65SrU1JY9o+2hPiE07MGINTnYZDENaiLk1GB1vv2Oj5/6w2C5g5oT5lAh/e/2Ps6789ucITM7iP3BkkyR/TAwFQOx+pNZ8TpKH5ot+a3zQ9LrbuqyfaxOGaAzFOnOQ9g=
  file: dist/*
  skip_cleanup: true
  on:
    repo: dmooney65/fmradio
