language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    before_install:
    - npm i -g npm@latest
    - sudo apt-get install -y librtlsdr-dev libflac-dev rpm
  - os: osx
    before_install:
    - npm i -g npm@latest
    - brew install flac rtl-sdr
cache:
  directories:
  - node_modules
notifications:
  email: false
script:
- npm test
- npm run dist
deploy:
  provider: releases
  api_key:
    secure: CwPd/TKCocPc/6N9QHAKuRuHyqkIuPUwWIDuemdwh0bqmRd9YvQ5PMQuKtH+ZPx2LEuTuty7q4Ryvpy4PW5nfMgSDnWngxHLZ+6mPm3LaKKm3eJ97W8P1zkxruZMGfB6WdAdgbRFCmbYfaiiGy2XsSkgtBQhVvFMYm/2zwvDBePHMfswIk89Fu0iUoONx5RzUa7Ugv7N6fOtvBMg64JKWr6bJ377DLo3JQ9r4/qdXpK2a/LBynaJahmiDN6mxTBigWXQvsZanQkpwDQUqz0qKxow4bmNzrHhbEjXwNUtWk8QN5R5LbjFEn58VF8f379mDStkehYBKs+U468PoROAAgkHlh6IGyWSAXzbd5clII5u7Ry+TBRDCVjVxuTe9tADvMhdN+jZYM3QKVvN12yIwKjJB1OObETmuvro897dg7TJfV6gq5HcwYcSAXY2INEIlcmr25n5HxD5DyYiTZ8kXhPvkC2NWbd89MMW2jRUFDosSsbHuN/hKGrWF/bPBJfjAH7RrzaRHEmziM39njmqq9eG0xnb1+rW7U+KDbYIjY0+WSUh/ErJ8Xu3wkHlV9PGiYFdb13hi5dWrwfdHEHyH5Ugx6BSy4NAIvkY6Hfo/pVFz0H09b1uKX3cUkyzpQgPqq3XkovsiTWg1TxGT9QkD2GCw9ZmVPzO5cgoTu3WdyQ=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: dmooney65/fmradio
