language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    before_install:
    - npm i -g npm@latest
    - sudo apt-get install -y librtlsdr-dev libflac-dev rpm
#  - os: osx
#    before_install:
#    - npm i -g npm@latest
#    - brew install flac rtl-sdr
cache:
  directories:
  - node_modules
notifications:
  email: false
script:
- npm test
- npm run dist
deploy:
  provider: releases
  api_key:
    secure: XtsDhewbj+D9Gma7bsZbRbydkp5sbWQghSvXm5XmkQu5sXXF7IZX5thFZOgY2IK/emSxS+KmXu72DNT8TSkEniiwRod5da/TfBwGUjidULIP47WzVuObWpydeSpek5JsBwQIdSOx3yzO7eOhJyalnuz5eK7WkplBv9/NKLCmSkBFy4r+n0+Pyr9Ht/HGCcgd/wZZlpEVAeXl07clVYSGhrJTsgWcqcaZ0DTA9ToHex8g7NGg9jvtrC08+Xepuc8Bgzu41N3s7gfN9vmD9QyCxclS8vH3b76NPm0ugwHOU8cUTGCrinLI+W240P6f9F8tfVZDHci58Np0A63IrPCAFGop+e3gk30PuNCGT3yfGqTvYqiIFEPK5UuDpTmEoP8/u7b4aiyqtC2Nv4IEH+s5FZF3T0CWsx34g9G5PeNJjeDtxm0Oh4/mmo//T3/j3pGq8ze3oVuHUL1xLx7MfG8gNcUypWGZwpM6ah3in8rjFg4HtjPkMuwk7vOUtwNm0FE+aicrAjbaM28KB9E2jw5IB1SNtfItRpuN+W1zcqPP/5bdW3x+gCwpUSvhxylIgc3l2nkkxs+vB9KgZF9iuinNJ/XexPFqCGH+cRSh8imAyeH0M3wmj/5YU8Wn5oQVGdHgUTmmuYmuh4dqjHYAD6uKDDHvkMVvKB89xqJYVh3oRSI=
  file: dist/*
  on:
    repo: dmooney65/fmradio
